/**
 * Golden Standard Reference Charts
 *
 * Values captured from SE1 binary reader + Swiss Ephemeris WASM validation with:
 *   - Ayanamsa: Lahiri (SE_SIDM_LAHIRI = 1)
 *   - Nodes:    Mean (SE body 10 = SE_MEAN_NODE)
 *   - Mode:     Geocentric Sidereal
 *
 * SE1 reader verified against WASM (Mercury: ±0.006°, Sun: ±0.005°).
 * These are the ground-truth values for all unit tests.
 * Regenerated by regen_reference_charts.mjs from SE1 + WASM ephemeris.
 */

export interface PlanetRef {
    name:      string;
    longitude: number; // Sidereal, Lahiri
    sign:      number; // 1=Aries … 12=Pisces
    speed:     number; // deg/day
}

export interface ChartRef {
    label:    string;
    year:     number;
    month:    number;
    day:      number;
    hour:     number; // UTC
    minute:   number;
    second:   number;
    lat:      number;
    lon:      number;
    jd:       number; // Julian Day (UT)
    // Planets (sidereal Lahiri, geocentric)
    planets:  PlanetRef[];
    // WholeSign house cusps (1-12 start degrees)
    wsCusps:  number[];
    ascendant: number;
    mc:        number;
    // Panchanga
    panchanga: {
        tithiIndex:      number; // 1-30
        tithiName:       string;
        nakshatraIndex:  number; // 1-27
        nakshatraName:   string;
        nakshatraPada:   number; // 1-4
        yogaIndex:       number; // 1-27
        yogaName:        string;
        karanaIndex:     number; // 1-60
        karanaName:      string;
        varaIndex:       number; // 0=Sun…6=Sat
        varaName:        string;
    };
}

// ---------------------------------------------------------------------------
// Chart A — J2000 Epoch (2000-01-01 12:00 UTC, Greenwich)
// ---------------------------------------------------------------------------
export const CHART_A: ChartRef = {
    label:  'A_J2000',
    year: 2000, month: 1,  day: 1,
    hour: 12, minute: 0,   second: 0,
    lat: 51.4779, lon: 0.0015,
    jd: 2451545.0,
    planets: [
        { name: 'Sun',     longitude: 256.38771231293777,  sign: 9,  speed:  1.0262603507612766 },
        { name: 'Moon',    longitude: 16.305744468550472,  sign: 1,  speed: 15.29065570957755 },
        { name: 'Mercury', longitude: 275.96318416184135,  sign: 10, speed:  1.1040374300762323 },
        { name: 'Venus',   longitude: 268.7662901881233,   sign: 9,  speed:  1.2608480982748915 },
        { name: 'Mars',    longitude: 179.88091667881565,  sign: 6,  speed:  0.5283815508846601 },
        { name: 'Jupiter', longitude: 21.971368691890746,  sign: 1,  speed: -0.030855516223482482 },
        { name: 'Saturn',  longitude: 131.08572563714455,  sign: 5,  speed: -0.02890728031843537 },
        { name: 'Rahu',    longitude: 101.18745200000001,  sign: 4,  speed: -0.0529537648459959 },
        { name: 'Ketu',    longitude: 281.187452,          sign: 10, speed: -0.0529537648459959 },
    ],
    wsCusps:   [256.38771231293777, 286.38771231293777, 316.38771231293777, 346.38771231293777, 16.387712312937765, 46.387712312937765, 76.38771231293777, 106.38771231293777, 136.38771231293777, 166.38771231293777, 196.38771231293777, 226.38771231293777],
    ascendant:  256.38771231293777,
    mc:        0,
    panchanga: {
        tithiIndex:     10,
        tithiName:      'Shukla 10',
        nakshatraIndex: 2,
        nakshatraName:  'Bharani',
        nakshatraPada:  1,
        yogaIndex:      21,
        yogaName:       'Siddha',
        karanaIndex:    20,
        karanaName:     'Gara',
        varaIndex:      6,
        varaName:       'Shanivara',
    },
};

// ---------------------------------------------------------------------------
// Chart B — Modern Chart (1985-07-12 00:30 UTC, New Delhi)
// ---------------------------------------------------------------------------
export const CHART_B: ChartRef = {
    label:  'B_MODERN',
    year: 1985, month: 7,  day: 12,
    hour: 0,  minute: 30,  second: 0,
    lat: 28.6139, lon: 77.209,
    jd: 2446258.5208333335,
    planets: [
        { name: 'Sun',     longitude: 85.11087559376591,  sign: 3,  speed:  0.9540266304838951 },
        { name: 'Moon',    longitude: 351.8852768335082,  sign: 12, speed: 12.303216138127482 },
        { name: 'Mercury', longitude: 64.4937733036736,   sign: 3,  speed:  0.782785910706707 },
        { name: 'Venus',   longitude: 89.54613236768188,  sign: 3,  speed:  1.231026996356377 },
        { name: 'Mars',    longitude: 218.8040006298603,  sign: 8,  speed:  0.11690792486547252 },
        { name: 'Jupiter', longitude: 353.47269434425846, sign: 12, speed:  0.07684907612315328 },
        { name: 'Saturn',  longitude: 321.3863520193138,  sign: 11, speed: -0.02581532577892176 },
        { name: 'Rahu',    longitude: 21.32865001556013,  sign: 1,  speed: -0.0529537648459959 },
        { name: 'Ketu',    longitude: 201.32865001556013, sign: 7,  speed: -0.0529537648459959 },
    ],
    wsCusps:   [85.11087559376591, 115.11087559376591, 145.1108755937659, 175.1108755937659, 205.1108755937659, 235.1108755937659, 265.1108755937659, 295.1108755937659, 325.1108755937659, 355.1108755937659, 25.11087559376591, 55.11087559376591],
    ascendant: 85.11087559376591,
    mc:        0,
    panchanga: {
        tithiIndex:     23,
        tithiName:      'Krishna 8',
        nakshatraIndex:  27,
        nakshatraName:  'Revati',
        nakshatraPada:  2,
        yogaIndex:      6,
        yogaName:       'Atiganda',
        karanaIndex:    45,
        karanaName:     'Balava',
        varaIndex:      4,
        varaName:       'Guruvara',
    },
};

// ---------------------------------------------------------------------------
// Chart C — Unix Epoch (1970-01-01 00:00 UTC, Null Island)
// ---------------------------------------------------------------------------
export const CHART_C: ChartRef = {
    label:  'C_EPOCH70',
    year: 1970, month: 1,  day: 1,
    hour: 0,  minute: 0,   second: 0,
    lat: 0.0, lon: 0.0,
    jd: 2440587.5,
    planets: [
        { name: 'Sun',     longitude: 256.3946747216877,     sign: 9,  speed:  1.0150999225402302 },
        { name: 'Moon',    longitude: 285.08881405348427,    sign: 10, speed: 17.05882948596127 },
        { name: 'Mercury', longitude: 236.9592200185216,     sign: 8,  speed:  1.3744546786199408 },
        { name: 'Venus',   longitude: 299.8994536596779,     sign: 10, speed:  1.157062658921859 },
        { name: 'Mars',    longitude: 192.41411089209384,    sign: 7,  speed:  0.5990568158608767 },
        { name: 'Jupiter', longitude: 181.34446224821409,    sign: 7,  speed:  0.09260134935118458 },
        { name: 'Saturn',  longitude: 258.24573385334406,    sign: 9,  speed:  0.1734529947214014 },
        { name: 'Rahu',    longitude: 321.84758328169664,    sign: 11, speed: -0.0529537648459959 },
        { name: 'Ketu',    longitude: 141.84758328169664,    sign: 5,  speed: -0.0529537648459959 },
    ],
    wsCusps:   [256.3946747216877, 286.3946747216877, 316.3946747216877, 346.3946747216877, 16.394674721687693, 46.39467472168769, 76.3946747216877, 106.3946747216877, 136.3946747216877, 166.3946747216877, 196.3946747216877, 226.3946747216877],
    ascendant: 256.3946747216877,
    mc:        0,
    panchanga: {
        tithiIndex:     3,
        tithiName:      'Shukla 3',
        nakshatraIndex: 22,
        nakshatraName:  'Shravana',
        nakshatraPada:  2,
        yogaIndex:      14,
        yogaName:       'Harshana',
        karanaIndex:    5,
        karanaName:     'Taitila',
        varaIndex:      3,
        varaName:       'Budhavara',
    },
};

export const ALL_CHARTS: ChartRef[] = [CHART_A, CHART_B, CHART_C];
